version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "nawey"
  backend:
    build: ./backend-NestJS
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend-NextJS
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  data:
