version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "nawey"
  backend:
    build: ./backend
    ports:
      - "8080:8000"
    depends_on:
      - db
volumes:
  data:
